#######################
# "on push" Test Gate #
#######################
---
name: Main Workflow
on:
  push:
    branches:
      - 'main'


jobs:
  deploy:
    name: Build Base Container and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project at current commit
        uses: actions/checkout@v2
      - name: Build Base Image
        run: echo "Pass!"
